name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    if: ${{ github.event.pull_request.changed_files == 0 }}
    runs-on: ubuntu-latest

    steps:
      - name: Close Pull
        uses: peter-evans/close-pull@v1
        with:
          token: ${{ secrets.WIKIBOT_TOKEN }}
          comment: Auto-closing pull request
          delete-branch: true
